sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3.1
jdk:
  - openjdk8
node_js:
  - node
services:
  - redis
install:
  - npm install --global gulp-cli
script:
  - gulp
  - bundle exec jekyll build
notifications:
  email: false