sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3.1
services:
  - redis
before_install:
  - nvm install node
  - node -v
  - npm -v
  - npm install --global gulp-cli
  - npm install
script:
  - gulp
  - bundle exec jekyll build
notifications:
  email: false