# Site settings
title: Mkdebpack
description: Make .deb packages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mkdebpack.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: mkdebpack
user_description: mkdebpack
user_title: mkdebpack
email: mkdebpack@gmail.com
twitter_username: mkdebpack
github_username:  mkdebpack
gplus_username:  mkdebpack
disqus_username: mkdebpack

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor']
